#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('LIST_GITHUB_USERS_COMPOSER_INSTALL', $file);
        break;
    }
}

if (!defined('LIST_GITHUB_USERS_COMPOSER_INSTALL')) {
    die(
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

require LIST_GITHUB_USERS_COMPOSER_INSTALL;

use Hnw\SingleSubcommandConsole\Application; 
use Hnw\Command\ListGithubUsersCommand; 

$app = new Application('list-github-users', '0.0.1');
$app->add(new ListGithubUsersCommand());
$app->run();
